CC=gcc
CFLAGS=-Wall -g

one: one.c
	$(CC) $(CFLAGS) one.c -o one

two: two.c
	$(CC) $(CFLAGS) two.c -o two

three: three.c
	$(CC) $(CFLAGS) three.c -o three

four: four.c
	$(CC) $(CFLAGS) four.c -o four

seven: seven.c
	$(CC) $(CFLAGS) seven.c -o seven

eight: eight.c
	$(CC) $(CFLAGS) eight.c -o eight

clean: 
	rm *.o; rm one; rm two; rm three; rm four; rm seven; rm eight;
